### ISSUE TITLE
CSS合并成功了，但JS合并却出现了 400 Bad Request

### ISSUE THREAD

**Issue by jue** [seajs/seajs-combo#10]
启用了combo，CSS合并成功了，但JS合并却出现了 400 Bad Request

服务端配置：
concat on;
concat_max_files 30;

![a](https://f.cloud.github.com/assets/377499/2217272/fda47112-9a19-11e3-8440-0789efb2fee2.PNG)

这是为什么？ 求答解，谢谢！

**Comment by afc163** [comment]
给链接和demo吧，看不出来。

**Comment by jue** [comment]
demo给不出来，在内网
链接： http://s.XXX.com/scripts/sea-modules/??seajs/seajs/2.1.1/sea.js,seajs/seajs-combo/1.0.1/seajs-combo.js

![b](https://f.cloud.github.com/assets/377499/2217356/4d514c7a-9a1b-11e3-8b56-5f4f0a4a78c5.PNG)

**Comment by jue** [comment]
找到原因了

服务端编译的时候是application/x-javascript
如下：
static ngx_str_t  ngx_http_concat_default_types[] = {
    ngx_string("application/x-javascript"),
    ngx_string("text/css"),
    ngx_null_string
};

我的服务端是 application/javascrip

修改我的服务端 重启
或者 
修改 nginx-http-concat 重新编译
