### ISSUE TITLE
关于server side combo的疑问

### ISSUE THREAD

**Issue by lynzz** [seajs/seajs-combo#11]
公司原先有写一个加载器，有如下的注释

```
基于以下理由, 放弃Server Side Combo

1. 导致register必须在require之前;

2. 前端缓存群, 因为文件全部缓存到了内存里, 原来的模式, 内存占用量一定是小于等于文件总大小的. 用了SSC就会超过了.

3. 缓存Purge问题. 更新一个文件你都不知道要Purge哪些Key.

4. 维护成本高: 本来依赖是体现在模块里, 现在在Combo顺序上还要再体现一次.

5. 为了避免访问不同页面时, 大文件内容重复加载, jQuery这种一般不会设置为Combo项, 于是又要区分哪些要Combo, 哪些不要Combo;

6. 在Keep-Alive的情况下, 仅在JS/CSS上减小请求数带来的好处有多大没有数据支撑;

7. 带来好处有前提, 用户必须老是访问同类型页面, 那减小请求数明显; 要是用户访问的是五花八门的页面, 相同的代码被合在不同的Combo里, 会导致总下载量的增加.

```

个人能力有限，不是很了解 sever side combo, 以下属个人理解，按问题顺序回答：
1. 本身加器的问题，用seajs应不存在这个问题
2. 不懂
3. 不懂
4. seajs-combo 会根据模块依赖进行combo,不存在维护成本
5. seajs-combo 可设置
6. 不清楚，不知支付宝这种大数量，能否体现出来在JS/CSS上减小请求数带来的好处
7. 不懂

希望高人指点

**Comment by popomore** [comment]
1. 应该是你们的内部实现，不懂
2. 这里你们是用了本地缓存？如果是的话 combo 是可以按模块缓存，不需要按整个 combo 地址缓存
3. 我们的实现方式是非覆盖式的，所以不需要更新。需要更新的方案确实比较复杂，要清除所有包含某个模块的缓存。
4. 依赖顺序应该是由 loader 处理的，combo 只是合并请求
5. 可设置
6. 文件总是要请求的，合并总比不合并好（不清除具体业务场景）
7. 并非一个页面访问一次，如果一个页面访问几百万次，那 combo 的链接应该也是相同的

**Comment by lynzz** [comment]
感谢 @popomore 的解答

**Comment by lynzz** [comment]
感谢 @popomore 的解答
