### ISSUE TITLE
??不是出现在根目录下

### ISSUE THREAD

**Issue by looping84** [seajs/seajs-combo#12]
用了下combo，发现，发起的请求是这个样：

```
http://localhost:18080/sea-modules/arale/??popup/1.1.5/
```

还有这个样的，

```
http://localhost:18080/sea-modules/??arale
```

怎么配置才能得到

```
 http://localhost:18080/??a.js,b.js
```

**Comment by popomore** [comment]
就是这样的

**Comment by looping84** [comment]
那服务器端，全部得对所有的url进行过滤，查找 **??**的url，再处理么。
这样感觉，效率太低啊
我打算用node写个ngix的combo功能

**Comment by popomore** [comment]
nginx 可以用这个 https://github.com/alibaba/nginx-http-concat
node 可以用 https://github.com/popomore/combo2
