### ISSUE TITLE
使用combo后读取配置文件问题

### ISSUE THREAD

**Issue by silvmind** [seajs/seajs-combo#13]
var Popup = require('./popup');
var defaults = require('./dialog-config');
var css = defaults.cssUri;
使用combo后上面2个请求会合并到一个请求，但是“defaults ”就会无法取值

**Comment by afc163** [comment]
浏览器？文件格式？seajs 版本？可重现页面？

**Comment by silvmind** [comment]
这是artDialog v6版本的源文件，我引入combo插件后就提示defaults下没有值
浏览器：chrome 34
seajs：2.1.1
combo：1.0.1
