### ISSUE TITLE
seajs-combo 与 时间戳 问题

### ISSUE THREAD

**Issue by stoneChen** [seajs/seajs-combo#14]
顶部设置了时间戳

``` js
seajs.config({
    map: [
        [ /^(.*(?:\/app)\/.*\.(?:css|js))(?:.*)$/i, '$1?t=1401962945804' ]
    ]
})
```

通过seajs-combo插件生成了如下uri
http://res.static.cn/assets/sea-modules/??a.js?t=1401962945804,b.js?t=1401962945804,c.js?t=1401962945804
但是combo服务器只返回了a.js的内容,b.js和c.js都没有返回
后来发现,是时间戳的问题,时间戳不能每个文件后都加,只能加在最后,也就是说,类似于下面这样才可以返回a.js,b.js,c.js三个文件的内容
res.static.cn/assets/sea-modules/??a.js,b.js,c.js?t=1401962945804
有好的解决办法吗? 

后来发现支付宝官方combo服务器也有这个问题,比如
https://a.alipayobjects.com/??seajs/seajs/2.1.1/sea.js?t=111,jquery/jquery/1.7.2/jquery.js?t=234
只返回了sea.js的内容,而没有jquery的内容,把前面那个?t=111去掉就可以了.

难道只能通过模块版本号(package.json中配置的)避免缓存?

**Comment by afc163** [comment]
@army8735

**Comment by hotoo** [comment]
这里有几个概念：
1. 客户端缓存
2. 服务端缓存
3. 服务端合并服务(combo)
4. 版本控制

对于生产环境，只需要通过合理的策略，保证用户客户端缓存策略合理即可。而这个最好使用版本策略，或添加一个时间戳即可，无需每个文件后添加时间戳。

你说支付宝官方 combo 服务器只返回第一个文件的内容的情况，是 Nginx 合并服务模块的特性（或者说 BUG）。

对于服务端的合并服务缓存策略，最好是使用版本策略，否则合并服务无法服务端缓存。

如果是开发环境，可以参考 https://github.com/seajs/seajs/issues/264#issuecomment-20719662

**Comment by stoneChen** [comment]
@hotoo 
可能我需要介绍一下我们模块部署的方案:
像seajs及其插件,gallery下所需所有模块,jquery下jquery及其所需所有插件等开源类的模块,以及我们自己开发的公用性(业务性不太强)模块,结合spm私有源,都部署在一台单独的资源服务器上,具体项目的业务模块都只部署在项目中,当然这些业务模块也会根据"id与路径一致"等原则,通过spm合并打包压缩.

理由是,业务模块具有很强的变化性,经常改版本号,比较麻烦.通过配置spm的idleading选项,使打包出来的id,与"标准"模块 <code>family/name/version/name</code> 这种形式不同.不是特殊情况,这种我们这种id就不会改变了,一旦系统升级,通过更新时间戳(仅对于业务模块)让客户浏览器自动更新模块内容.也因此,我们的应用服务器与资源服务器都需要部署combo服务.

以上你说的这几点,我基本都了解,我们在使用combo前,这样的时间戳策略是没问题的,用了combo服务后(当然这需要增加seajs-combo插件配合),会产生这样的问题,我之前也未曾料到,于是我也想办法,怎么样才能只在最后添加时间戳,查看了seajs-combo源码以及官方文档,此插件貌似只有comboSyntax, comboMaxLength, comboExcludes这三个参数可以配置.于是无从下手...希望能给出一些建议.

ps:截止目前为止,经打包测试,除了此问题,项目都能正常运行.

**Comment by army8735** [comment]
url规则中?后的会被忽略，规则是这样，combo后反而有这个问题……

combo的时候如果都有timestamp的话取最大的那个放在最后？

**Comment by stoneChen** [comment]
@army8735 
这么说这确实是一个问题咯?
在不升级seajs-combo的情况下有解决办法么?

另外,如果要升级的话,我建议,可以提供一个参数比如叫comboSuffix,值为类似于"?t=12345"这样的,直接追加到拼好的uri末尾,如果是其他"不合规范"的值,比如"12323",而导致404,则交给用户去解决

**Comment by stoneChen** [comment]
@army8735 好些天没上github，原来这个问题已经解决了啊，赞一个！待会更新下来试一下

**Comment by stoneChen** [comment]
@army8735  这次代码更新，源上没有更新版本吗，还是1.0.1？ 查了下spm2和spm3上都还是1.0.1

**Comment by army8735** [comment]
没……直接就着新的seajs3.0基础上改的，而3.0还没发……

**Comment by stoneChen** [comment]
@army8735  我发现seajs2.3在spm2的源上就已经找不到了，估计3.0也不会有吧。是不是以后spm2源上的代码不再更新了？ 我们这边暂时还没计划升级到spm3呢

**Comment by shi2713** [comment]
更新了最新版本的sejajs-combo以及sea.js(3.0)，这个版本如何拼接的js尾部加时间戳？

已解决：comboSuffix: '?v=1',
