### ISSUE TITLE
spm install seajs/seajs-combo 在spm3 无法安装

### ISSUE THREAD

**Issue by huixisheng** [seajs/seajs-combo#15]
spm3 如下命令无法安装，应该是所有的seajs的插件都有这个问题
## Install

Install with spm:

$ spm install seajs/seajs-combo

修改为 
$ spm install seajs-combo 就可以。但是这样安装会把 seajs-combo整个开发目录都安装下来，其实我们使用的时候应该需要的是 dist目录中的文件即可。应该是这样

```
seajs-combo
                    |-- 1.0.1
                              |-- seajs-combo.js
                              |-- seajs-combo-debug.js
```

**Comment by army8735** [comment]
明天看看

**Comment by afc163** [comment]
spm install seajs-combo，spm3 没有 family 了。
