### ISSUE TITLE
使用seajs-combo合并时浏览器提示403，而且返回的文档类型为text/html？？？

### ISSUE THREAD

**Issue by landy2014** [seajs/seajs-combo#16]
谷歌浏览器报错如下：

Request URL:http://www.kinhom.com/sea-modules/kinhompc/v1/1.0.0/??index.js,send_sms.js
Request Method:GET
Status Code:403 Forbidden

我的服务器配置如下：

location /sea-modules/kinhom/v1/1.0.0/{
       concat on;
       concat_max_files 20;
}

难道真的要每级目录都配置吗？？
请高手指点；

**Comment by army8735** [comment]
你这个让人如何回答……

**Comment by landy2014** [comment]
抱歉，没描述清楚，已经找到解决方法了，是需要在nginx服务器的conf里面设置每一层的目录。就正常了。
