### ISSUE TITLE
中文文档

### ISSUE THREAD

**Issue by lifesinger** [seajs/seajs-combo#3]
# combo 插件

减少 HTTP 请求数是性能优化中非常重要的一条准则。使用 combo 插件，配合服务器的 [nginx-http-concat](https://github.com/taobao/nginx-http-concat) 服务（[安装指南](https://github.com/seajs/seajs/issues/337)），可自动对同一批次的多个模块进行合并下载。
## 使用场景

``` js
seajs.use(['a', 'b'], ...);

require.async(['a', 'b'], ...);

define('id', ['a', 'b'], ...);
```

上面这些场景中的 `a.js` 和 `b.js` 可以合并成 `http://example.com/path/to/??a.js,b.js` 一起下载。
## 引入方式

使用很简单，只要加载 `sea.js` 时，同时加载 `seajs-combo.js` 即可：

``` html
<script src="http://test.com/??path/to/sea.js,path/to/seajs-combo.js"></script>
```

或者在 sea.js 之后用 `script` 引入：

``` html
<script src="path/to/sea.js"></script>
<script src="path/to/seajs-combo.js"></script>
```

推荐用 `??path/to/sea.js,path/to/seajs-combo.js` 的方式激活，这可以少一个请求。

**提示**：其他需要线上使用的插件，都推荐通过 `??path/to/sea.js,path/to/seajs-xxx.js` 的方式使用。
### comboSyntax `Array`

加载 combo 插件后，可以通过 `comboSyntax` 配置更改 combo 规则：

``` js
seajs.config({
  comboSyntax: ['?', '&']
})
```

上面的配置，会将 combo 规则改成类 YUI Loader 的形式：`http://example.com/path/to/?a.js&b.js`
### comboExcludes `RegExp | Function`

可以通过 `comboExcludes` 排除掉特定文件：

``` js
seajs.config({
  comboExcludes: /jquery\.js/ // 从 combo 中排除掉 jquery.js 
})
```

comboExcludes 可以是正则，也可以是一个函数：

``` js
seajs.config({
  comboExcludes: function(uri) {
    // 某些特定目录下的文件不合并
    if (uri.indexOf('/some/path/') > 0) {
      return true
    }
  }
})
```

在激活 combo 插件后，如果需要临时禁用 combo，可以

``` js
seajs.config({
  comboExcludes: /.*/
})
```

上面的配置把所有文件都排除掉了，因此 combo 也就不生效了。

**提示**：combo 插件已经做了去重等处理，已经下载或正在下载的，不会重复下载。
### comboMaxLength `Number`

combo 后的 URL 地址太长时，IE 以及有些服务器的配置会不支持。目前最佳经验值是不超过 2000 个字符。

``` js
seajs.config({
  // 将 combo URL 的最大长度修改为 1000 个字符
  comboMaxLength: 1000
})
```
### 测试页面

http://seajs.github.io/seajs/tests/specs/extensible/test.html?seajs-combo

**Comment by w3cpress** [comment]
我想问下这个插件必须配合服务器，才能用么？

**Comment by popomore** [comment]
对，服务器要支持 combo

```
—
```

**Comment by w3cpress** [comment]
@popomore 那我本地测试，是不是要在apche的配置下，就可以看到了呢？有参考链接地址么？

**Comment by popomore** [comment]
可以看下这个

https://github.com/alibaba/nginx-http-concat

**Comment by alvin2ye** [comment]
静态资源一般会用 CDN 服务， 没有自动支持 combo 的CDN服务商呢?

**Comment by luhang02** [comment]
我自己实现了一个combo,直接写请求地址是能够成功的,但是这个插件不会自动给我合并请求,是不是他会到服务端验证过能不能combo

**Comment by popomore** [comment]
@luhang02 看看你怎么用的，不会去服务端验证的

**Comment by luhang02** [comment]
<script src="/static/??seajs/seajs/2.1.1/sea.js,seajs/seajs-combo/1.0.1/seajs-combo.js,seajs/seajs-style/1.0.2/seajs-style.js,seajs/seajs-log/1.0.1/seajs-log.js,jquery/jquery/1.7.2/jquery.js,gallery/json/1.0.3/json.js" charset="utf-8" id="seajsnode" onerror="window.monitor && monitor.lost && monitor.lost(this.src)"></script>  

 seajs.use(['jquery', 'custom/jbox/1.0.0/xbox'], function (jQuery, jbox) {}

 define("custom/jbox/1.0.0/jbox", ["$", "arale/dialog/1.2.5/dialog", "arale/overlay/1.1.4/overlay", "arale/position/1.0.1/position", "arale/iframe-shim/1.0.2/iframe-shim", "arale/widget/1.1.1/widget-debug", "arale/base/1.1.1/base", "arale/class/1.1.0/class", "arale/events/1.1.0/events", "arale/overlay/1.1.4/mask"]

 jbox用到的模块他不合并请求

**Comment by popomore** [comment]
先请求 jbox 才知道依赖的是什么，这个是 combo 的原理。

**Comment by luhang02** [comment]
jbox单独请求这个我明白，jobx里的他还是单独请求
 seajs.use(['a', 'b'], ...);

require.async(['a', 'b'], ...);

define('id', ['a', 'b'], ...);

上面这些场景中的 a.js 和 b.js 可以合并成 http://example.com/path/to/??a.js,b.js 一起下载。  
 我jbox属于第3种场景，他依赖的那些还是单独下载，不合并

**Comment by popomore** [comment]
了解，使用 1.0.0 版吧。

**Comment by luhang02** [comment]
谢谢，1.0.0正常了
 还有一个问题，我在地址后面加了seajs-debug右下角出来的界面和文档上的界面不一样，出来一个Config File: 的输入框，各种按钮没有

**Comment by luhang02** [comment]
我某个页面所有模块想都放到一个use里，然后让他合并加载，如果某个模块被重复引用好像会出错，比如这样
seajs.use(['jquery', 'arale/dialog/1.2.5/dialog', 'arale/dialog/1.2.5/confirmbox']

**Comment by afc163** [comment]
出了什么错，给出更多的信息，最好有可访问的地址。

**Comment by wangjianjun** [comment]
combo有时间戳的配置么？

**Comment by henryzp** [comment]
@afc163 ，我现在碰到个问题，就是我的网站是www.test.com，但资源文件都放在images.test.com里面，也就是说combo出来的结果不能是www.test.com??a.js，这种，必须是我指定的域名，是可以配置的，不能写死的？请问该如何实现

**Comment by army8735** [comment]
seajs.config({
  base: 'images.test.co'
})

**Comment by henryzp** [comment]
@army8735 谢谢。。

**Comment by gaocc2016** [comment]
commbo 和懒加载 互相矛盾么

**Comment by henryzp** [comment]
@gaocc ，这两个是不同的概念吧。。commbo，我的理解就是将多个请求，合并成同一个请求，就是表现在URL的上面。而懒加载是DOM元素，比如说页面中可以先展示一屏的数据，另外几屏的DOM放在textarea标签中，或者是将图片进行懒加载。。矛盾一词是指什么？

**Comment by testxin** [comment]
combo中setHash函数中为何把?后面的参数全部替换空字符串，目的是什么，这一个会导致map中映射的无效

**Comment by huhu0622** [comment]
window 系统不能装这个服务么？

**Comment by browneyedape** [comment]
请问 做combo的时候 
require（a）;require(b); 是否等同于 define(id,['a','b'],factory){}里面的依赖？
因为我使用的时候两个require会一起下载。
 为何不做成可控制是否 combo?

**Comment by browneyedape** [comment]
var x =require（a）; var y = require(b);  //combo
这时候 x里面包含了require(b)的内容，并且 y undefined 了。
然后 我只能 y=y||x; 来让开发环境和combo环境一致。。。
这样子好吗。。

**Comment by popomore** [comment]
combo 文件里必须定义 id

—
通过 Mailbox 发送

**Comment by browneyedape** [comment]
那就必须要用spm？感觉那个好难用的样子。。

**Comment by popomore** [comment]
不用 spm 自己生成 id 依赖也可以，spm 只是遵循 seajs 的规则生成

—
通过 Mailbox 发送

**Comment by shi2713** [comment]
启用了combo，通过map配置了时间戳，然后在拼接js处不起做用。单个js可以，求助。
配置：
    map:[['.js','.js?v=1']]
补充：使用的最新版，刚试了下上个版本可以。输出的结果是http://xxx.com/a.js?v=1,b.js?v=1
现在最新版的话是有什么替代方案了吗？

已解决：comboSuffix: '?v=1',

**Comment by lijialiang** [comment]
入口：

```
     seajs.use(['b.js']);
```

b模块：

```
    define('b',function(require, exports) {
        var a = require('a');
        console.log(a);
    });
```

a模块单独加载出来了，有什么办法可以加入combo里？

**Comment by eijil** [comment]
碰到个问题,有三个文件

<pre>a.js // require b.js<br/>b.js // require c.js<br/>c.js</pre>

入口

<pre>seajs.use('a');</pre>

a.js和b.js会合并成一个 但c.js单独一个连接 
这是为什么 只支持一级？

**Comment by wy-ang** [comment]
说实话，这个教程看了N遍了还是一脸的懵逼（nginx已经配置好了）；
