### ISSUE TITLE
找不到seas.Module对象

### ISSUE THREAD

**Issue by charmingzuo** [seajs/seajs-combo#5]
var Module = seajs.Module;
var FETCHING = Module.STATUS.FETCHING;
这句出现脚本错误，提示 Module 为undefined。查看了一下seajs的成员，确实没有Module这个东西，在官方文档中也没有找到 seajs.Module 的相关资料，求解惑。

**Comment by lizzie** [comment]
seajs 有吗? seajs 版本多少. seajs.org 上都有的

**Comment by lifesinger** [comment]
升级到 Sea.js  2.1.1 版本。 1.x 版本的确没有。
