### ISSUE TITLE
引入combo插件发出的请求还是和没引入之前一样

### ISSUE THREAD

**Issue by weekeight** [seajs/seajs-combo#6]
<ol style="list-style-type: decimal;" class=" list-paddingleft-2">
    <li>
        <p style="text-align: left;">
            <span style="line-height: 0px;"><span style="line-height: 0px;">﻿</span>﻿</span>项目index.html正常引入seajs2.1.1和seajs-combo1.0.1两个js文件
        </p>
    </li>
    <li>
        <p style="text-align: left;">
            在index.html使用seajs.use(&#39;src/test.js&#39;)来启动模块
        </p>
    </li>
    <li>
        <p style="text-align: left;">
            在src目录下有三个文件如下：
        </p>
    </li>
    <ul style="list-style-type: disc;" class=" list-paddingleft-2">
        <li>
            <p style="text-indent: 0em; text-align: left;">
                test.js
            </p>
        </li>
        <pre class="brush:html;toolbar:false">define(&#39;src/test&#39;,[&#39;src/a.js&#39;, &#39;src/b.js&#39;], function(require,exports, module){
var a = require(&#39;src/a.js&#39;);
var b = require(&#39;src/b.js&#39;);
debugger;
})</pre>
        <li>
            <p style="text-indent: 0em; text-align: left;">
                a.js
            </p>
        </li>
        <pre class="brush:html;toolbar:false">define(&#39;src/a.js&#39;,[],function(require,exports,module){
module.exports = {
module : &#39;a&#39;
}
})</pre>
        <li>
            <p style="text-indent: 0em; text-align: left;">
                b.js
            </p>
        </li>
        <pre class="brush:html;toolbar:false">define(&#39;src/b.js&#39;,[],function(require,exports,module){
module.exports = {
module : &#39;b&#39;
}
})</pre>
        <p dir="ltr">
            现在我的服务器是不支持combo的，但是前端这边发请求的时候既然引入了seajs-combo它发出的请求抓包不是能看到例如***/??a.js,b.js这样的合并请求么？
        </p>
        <p dir="ltr">
            还是说seajs会先去检测服务器是否支持combo，如果支持才那样发请求？
        </p>
    </ul>
</ol>

**Comment by popomore** [comment]
请使用 seajs-combo1.0.0，1.0.1 是和 seajs 2.2.0 配合的。

**Comment by hotoo** [comment]
需要服务器支持 combo 才有效的。

单纯客户端以 combo 的方式发起请求，而服务端不支持的话，是达不到效果的，可能发生 404 这样的错误。

**Comment by weekeight** [comment]
<p>
  @popomore   是因为版本的问题导致没发出那样的请求？另外，我在<a href="https://github.com/seajs/seajs-combo" target="_self" title="">https://github.com/seajs/seajs-combo</a>上面找不到seajs-combo1.0.0的版本，请问去哪里能找到呢？谢谢！
</p><p>
  @hotoo   我用来测试的服务器是apache的不支持combo，我后面会放到支持combo的服务器上。问题是现在发出去的请求不是combo合并后的请求，解决这个问题才行
</p>

**Comment by popomore** [comment]
spm install seajs/seajs-combo@1.0.0

**Comment by weekeight** [comment]
@popomore 只能通过这种方式么？我公司的开发机是不能连外网的，平常都是直接下载了把文件拷过去的。能不能贴一下它的下载地址？

**Comment by popomore** [comment]
不能本地下来再传上去？

**Comment by weekeight** [comment]
@popomore 恩，我平常装一些grunt的模块的时候是这么做的。可是我在window（本地）装的spm，安装插件的时候不成功，提示‘connect ETIMEOUT'这样的错误，是因为公司网络墙了。而我的npm install我配了proxy就可以了，而spm的我找不到配置proxy的命令。（PS：github编辑issue不支持富文本好纠结，还是我没发现？）

**Comment by popomore** [comment]
http://assets.spmjs.org/seajs/seajs-combo/1.0.0/seajs-combo.js

github 是 markdown 呀

**Comment by weekeight** [comment]
@popomore 非常感谢！学习了！

**Comment by weekeight** [comment]
<p>
@popomore 
    在有cgi这一层的时候seajs-combo是不是不太一样？我现在的测试项目结构如下：
</p>

<ul class=" list-paddingleft-2" style="list-style-type: circle;">
    <li>
        <p>
            zh_CN
        </p>
    </li>
    <ul class=" list-paddingleft-2" style="list-style-type: disc;">
        <li>
            <p>
                modules
            </p>
        </li>
        <ul class=" list-paddingleft-2" style="list-style-type: square;">
            <li>
                <p>
                    seajs/seajs/2.1.1/sea.js
                </p>
            </li>
            <li>
                <p>
                    seajs/seajs_modules/seajs_combo/1.0.0/seajs-combo.js
                </p>
            </li>
        </ul>
        <li>
            <p>
                src
            </p>
        </li>
        <ul class=" list-paddingleft-2" style="list-style-type: square;">
            <li>
                <p>
                    test.js
                </p>
            </li>
            <li>
                <p style="margin-bottom: 5px; line-height: normal;" dir="ltr">
                    a.js
                </p>
            </li>
            <li>
                <p style="margin-bottom: 5px; line-height: normal;" dir="ltr">
                    b.js
                </p>
            </li>
        </ul>
    </ul>
</ul>

<p style="margin-bottom: 5px; line-height: normal;" dir="ltr">
    项目的入口在frame_html.html里面，这个是cgi模板，代码如下：
</p>

<pre class="brush:html;toolbar:false">&lt;!DOCTYPE html&gt;
&lt;html&gt;
&lt;head&gt;
&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=Edge&quot;&gt;
&lt;meta name=&quot;keyword&quot; content=&quot;&quot;&gt;
&lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no&quot;&gt;
&lt;title&gt;test&lt;/title&gt;
&lt;script type=&quot;text/javascript&quot; src=&quot;&lt;%@GetResFullName($js_path$modules/seajs/seajs/2.1.1/sea.js)%&gt;&quot;&gt;&lt;/script&gt;
&lt;script type=&quot;text/javascript&quot; src=&quot;&lt;%@GetResFullName($js_path$modules/seajs/seajs_modules/seajs_combo/1.0.0/seajs-combo.js)%&gt;&quot;&gt;&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;h1&gt;test&lt;/h1&gt;
&lt;script type=&quot;text/javascript&quot;&gt;
seajs.config({
base : &#39;&lt;%@GetResFullName($js_path$/)%&gt;&#39;,
alias : {
&#39;backbone&#39; : &#39;modules/gallery/backbone/1.0.0/backbone.js&#39;,
&#39;underscore&#39; : &#39;modules/gallery/underscore/1.4.4/underscore.js&#39;,
},
paths : {
&#39;cssPath&#39; : &#39;&lt;%@GetResFullName($css_path$/)%&gt;&#39;
},
comboExcludes : function(uri){
if(uri.indexOf(&#39;modules/&#39;)){ return true; }
}
});
seajs.use(&#39;&lt;%@GetResFullName($js_path$/src/test.js)%&gt;&#39;);
&lt;/script&gt;
&lt;/body&gt;
&lt;/html&gt;</pre>

<p>
    &nbsp;其中GetRestFullName是cgi模板函数，在返回给前端的html会先把模板变量$js_path$变为字符串‘<span style="color: rgb(34, 34, 34); font-family: Consolas, &#39;Lucida Console&#39;, monospace; font-size: 12px; white-space: pre-wrap; background-color: rgb(255, 255, 255);">cgi-bin/get_res?type=js&amp;p=</span>’，所以在头部引入的sea.js和seajs-combo.js，已经后面seajs.use那里的test.js都是通过get_res这个cgi返回的.<br/>
</p>

<hr/>

<p>
    test.js
</p>

<pre class="brush:html;toolbar:false">define(&#39;src/test&#39;,[&#39;src/a.js&#39;, &#39;src/b.js&#39;], function(require,exports, module){
var a = require(&#39;src/a.js&#39;);
var b = require(&#39;src/b.js&#39;);
debugger;
})</pre>

<p>
    a.js
</p>

<pre class="brush:html;toolbar:false">define(&#39;src/a.js&#39;,[],function(require,exports,module){
module.exports = {
module : &#39;a&#39;
}
})</pre>

<p>
    b.js
</p>

<pre class="brush:html;toolbar:false">define(&#39;src/b.js&#39;,[],function(require,exports,module){
module.exports = {
module : &#39;b&#39;
}
})</pre>

<hr/>

<p>
    如此一来，前端发出去的请求就跟没有combo一样了，如test.js这个请求是：
</p>

<p>
    ***<span style="color: rgb(34, 34, 34); font-family: Consolas, &#39;Lucida Console&#39;, monospace; font-size: 12px; white-space: pre-wrap; background-color: rgb(255, 255, 255);">/cgi-bin/get_res?type=js&amp;p=/src/test.js</span>
</p>

<p>
    <span style="color: rgb(34, 34, 34); font-family: Consolas, &#39;Lucida Console&#39;, monospace; font-size: 12px; white-space: pre-wrap; background-color: rgb(255, 255, 255);">a.js和b.js这两个js的请求分开来了，如下：</span>
</p>

<p>
    <span style="color: rgb(34, 34, 34); font-family: Consolas, &#39;Lucida Console&#39;, monospace; font-size: 12px; white-space: pre-wrap; background-color: rgb(255, 255, 255);">***/<span style="color: rgb(34, 34, 34); font-family: Consolas, &#39;Lucida Console&#39;, monospace; font-size: 12px; white-space: pre-wrap; background-color: rgb(255, 255, 255);">cgi-bin/get_res?type=js&amp;p=/src/b.js &nbsp;</span></span>
</p>

<p>
    <span style="color: rgb(34, 34, 34); font-family: Consolas, &#39;Lucida Console&#39;, monospace; font-size: 12px; white-space: pre-wrap; background-color: rgb(255, 255, 255);"><span style="color: rgb(34, 34, 34); font-family: Consolas, &#39;Lucida Console&#39;, monospace; font-size: 12px; white-space: pre-wrap; background-color: rgb(255, 255, 255);">***/<span style="color: rgb(34, 34, 34); font-family: Consolas, &#39;Lucida Console&#39;, monospace; font-size: 12px; white-space: pre-wrap; background-color: rgb(255, 255, 255);">cgi-bin/get_res?type=js&amp;p=/src/a.js</span></span></span>
</p>

<p>
    这是为什么呢？我猜想是id不匹配的问题，可是我尝试改过id也不行
</p>

<p>
    我查看seajs.cache的结果如下：(ps:qspace.manniu.qq.com是我们开发机的域名)
</p>

![image](https://f.cloud.github.com/assets/1918022/1434852/4bd4c542-412a-11e3-8ca1-a2d64cfb94e4.png)

<p>请问我这里的问题是什么呢？seajs-combo的合并加载机制是怎样的呢？</p>

**Comment by hotoo** [comment]
楼上辛苦了，注意评论输入框右上角有一个 [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown) 可以看看

另外可以参考 http://daringfireball.net/projects/markdown/basics

**Comment by popomore** [comment]
静态文件为什么要过 cgi？ 注意是合并 url 而不是合并参数。

**Comment by weekeight** [comment]
@hotoo 刚刚才知道github原来是这样的，还害得我跑去用富文本编辑完再贴过来。。呵呵
@popomore 静态文件要过cgi这个有一些历史原因，对我现在这块工作来说我还暂时不清楚其作用是什么（会不会跟cdn有关）我刚问了一下其他同事，还没答复。（PS：因为我还是实习生，进公司不是很久有些东西还不清楚）
另外，文件是经过cgi返回的和直接引用静态资源会有区别么？（我测试的结果是直接引用服务器上的静态资源的话，combo就会启用，请求会合成一个）
还有，你说的‘注意是合并 url 而不是合并参数’我感觉我理解不是很透彻，能说细一点么？谢谢了！

**Comment by weekeight** [comment]
@popomore 我琢磨了一下，是不是指这两个url合并不成一个？

<p>
    <a href="http://qspace.manniu.qq.com/cgi-bin/get_res?type=js&amp;p=/src/a.js
" _src="http://qspace.manniu.qq.com/cgi-bin/get_res?type=js&amp;p=/src/a.js
">http://qspace.manniu.qq.com/cgi-bin/get_res?type=js&amp;p=/src/a.js&nbsp;</a>
</p>

<p>
    <a href="http://qspace.manniu.qq.com/cgi-bin/get_res?type=js&amp;p=/src/b.js" _src="http://qspace.manniu.qq.com/cgi-bin/get_res?type=js&amp;p=/src/b.js">http://qspace.manniu.qq.com/cgi-bin/get_res?type=js&amp;p=/src/b.js</a>&nbsp;<br/>
</p>

**Comment by popomore** [comment]
combo 规则是这样的，比如两个文件 `http://qspace.manniu.qq.com/a.js` `http://qspace.manniu.qq.com/b.js` 会合并成 `http://qspace.manniu.qq.com??a.js,b.js`，对，是两个问号。

如果用你们的规则可以生成 `http://qspace.manniu.qq.com/cgi-bin/get_res?type=js&p=/src/a.js,/src/b.js`，但是 combo 插件需要改下。

但是有个比较严重的问题，就是请求路径和模块路径不匹配，require 的时候会找不到路径。

**Comment by weekeight** [comment]
@popomore 刚找很多同事了解过，由于各种历史原因没谁知道为什么获取静态文件要经过cgi，现在我把它改成直接获取静态资源好了。。很感谢你的指导！thx！
