### ISSUE TITLE
使用combo之后confirmbox组件报错

### ISSUE THREAD

**Issue by billwing** [seajs/seajs-combo#7]
![image](https://f.cloud.github.com/assets/3411815/1712771/cbb36f9e-617c-11e3-93ca-e0e52505ed66.png)
如图，Chrome报错如下：

```
Uncaught TypeError: Cannot call method 'extend' of null  confirmbox.js:1
```

去掉`seajs/2.1.1/seajs-combo.js`就正常了
@lifesinger 玉伯，这是什么问题啊？

**Comment by lifesinger** [comment]
信息太少，无法帮助到你，很抱歉。

建议做一个可重现错误的页面。

On Tue, Dec 10, 2013 at 5:28 PM, Billwing notifications@github.com wrote:

> [image: image]https://f.cloud.github.com/assets/3411815/1712771/cbb36f9e-617c-11e3-93ca-e0e52505ed66.png
> 如图，Chrome报错如下：
> 
> Uncaught TypeError: Cannot call method 'extend' of null  confirmbox.js:1
> 
> 去掉seajs/2.1.1/seajs-combo.js就正常了
> @lifesinger https://github.com/lifesinger 玉伯，这是什么问题啊？
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/seajs/seajs-combo/issues/7
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by afc163** [comment]
在线可访问的，这样好定位问题。否则就像射覆一样，太高难度了。

**Comment by billwing** [comment]
好的，demo如下：
http://billwing.github.io/seajs-test.html

**Comment by afc163** [comment]
combo 插件需要和 `具名模块` 来结合使用，这样才能在同一个文件中通过 ID 来区分不同的 define 模块。

具体可以参考：https://github.com/seajs/seajs/issues/426

**Comment by billwing** [comment]
嗯嗯，明白了，犯了低级错误~
