### ISSUE TITLE
问个问题，照着给的例子来做，一直报400错误，能不能问一下主要是什么问题呢？

### ISSUE THREAD

**Issue by elover** [seajs/seajs-combo#9]
chrome下报错：
Request URL:http://localhost/sea-modules/arale/??class/1.1.0/class-debug.js,events/1.1.0/events-debug.js
Request Method:GET
Status Code:400 Bad Request
Request Headersview source

**Comment by popomore** [comment]
本地不支持 combo 吧

**Comment by elover** [comment]
我安装了nginx，也安装了nginx-http-concat
       nginx.conf中添加了配置如下：
        autoindex on;  # 支持罗列
        location /sea-modules {
            concat on;
            concat_max_files 20;
        }

**Comment by popomore** [comment]
每级目录都要配的

**Comment by elover** [comment]
谢谢你的回答，有没有办法测试一下nginx-http-concat 安装是否正确，对nginx配置不是很懂，安装的版本是nginx-1.5.7

**Comment by popomore** [comment]
root 没指定?

本地调试的话可以试试这个  https://github.com/popomore/combo2

**Comment by elover** [comment]
root设置了，但似乎不起作用，那像我上面的请求应该怎么配呢？非常感谢，对服务器配置不是能懂，准备把本地配好了，再去说服运维的也配好，平时也用了aralejs，请求太多了，性能不好，你刚说过的试过了，但是我们的http服务器不会去用node

**Comment by popomore** [comment]
```
location /sea-modules/ {
  root path/to/sea-modules;
  concat on;
  concat_max_files 20;
}
```

我们就是类似这样的，再不行试试 `location /`。

**Comment by elover** [comment]
我是照这个配的Issue #337，里面有些都是摸索的配好的，还是不行哦。以后能不能给个nginx的例子，谢谢了

**Comment by afc163** [comment]
这个去 nginx 的社区问效果会更好，和 seajs 关系不是很大。

或者这里：https://github.com/alibaba/tengine

**Comment by elover** [comment]
非常感谢，问了一下，这样设置就好了
location /sea-modules/ {
            concat_types "application/javascript" "text/css";
            concat on;
            concat_max_files 20;
        }
希望seajs越来越好，spm生态环境也越来越好哈！顺便说一下aralejs是我看过最赞的前端解决方案
